-- Diatomlife seed (auto-generated from src/app/data/products.ts)
-- Safe to run multiple times. Run AFTER full_setup.sql.
-- NOTE: prices are USD->KES placeholders at 130/USD. Correct real prices in Admin.

BEGIN;

-- 1) Categories
INSERT INTO public.categories (name, slug, sort_order) VALUES
('Minerals & Structural Support', 'minerals-and-structural-support', 1),
('Vitamins & Antioxidants', 'vitamins-and-antioxidants', 2),
('Detox & Cleanse', 'detox-and-cleanse', 3),
('Adaptogens & Stress Support', 'adaptogens-and-stress-support', 4),
('Blood Purification & Skin', 'blood-purification-and-skin', 5),
('Topical Wellness & Lymphatic', 'topical-wellness-and-lymphatic', 6),
('Herbal Teas & Relaxation', 'herbal-teas-and-relaxation', 7),
('Respiratory & Immune', 'respiratory-and-immune', 8),
('Raw Sweeteners & Energy', 'raw-sweeteners-and-energy', 9),
('Minerals & Sleep Support', 'minerals-and-sleep-support', 10),
('Anti-Inflammatory & Joint Health', 'anti-inflammatory-and-joint-health', 11),
('Minerals & Thyroid Support', 'minerals-and-thyroid-support', 12),
('Immune Support', 'immune-support', 13),
('Superfoods & Detox', 'superfoods-and-detox', 14),
('Superfoods & Nutrition', 'superfoods-and-nutrition', 15),
('Respiratory & Heart Health', 'respiratory-and-heart-health', 16),
('Minerals & Cellular Absorption', 'minerals-and-cellular-absorption', 17),
('Liver Support & Detox', 'liver-support-and-detox', 18),
('Digestive Health & Focus', 'digestive-health-and-focus', 19)
ON CONFLICT (slug) DO UPDATE SET name = EXCLUDED.name;

-- 2) Products
INSERT INTO public.products (name, slug, category_id, price_kes, description, holistic_story, scientific_why, ingredients, benefits, usage, image_url, stock_quantity, is_active) VALUES
('Nutrisil', 'nutrisil', (SELECT id FROM public.categories WHERE slug = 'minerals-and-structural-support'), 3249, 'Food-Grade Diatomaceous Earth - Ancient mineral support for structural integrity and natural cleansing.', 'Derived from ancient freshwater diatoms, Nutrisil is earth''s hidden treasure for internal structural integrity. It works to gently "sweep" the digestive tract while providing the essential minerals to help you glow from the inside out.', 'A concentrated source of amorphous Silica, which is vital for collagen formation, bone density, and strengthening the connective tissues in hair, skin, and nails.', array['Food-Grade Diatomaceous Earth', 'Amorphous Silica', 'Natural Trace Minerals']::text[], array['Supports collagen production', 'Strengthens hair, skin & nails', 'Gentle digestive cleanse', 'Bone density support']::text[], 'Mix 1 teaspoon into a glass of water or juice daily on an empty stomach.', 'https://images.unsplash.com/photo-1704650312022-ed1a76dbed1b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxkaWF0b21hY2VvdXMlMjBlYXJ0aCUyMHBvd2RlciUyMG5hdHVyYWwlMjBzdXBwbGVtZW50fGVufDF8fHx8MTc3MTc1OTc4NXww&ixlib=rb-4.1.0&q=80&w=1080', 50, true),
('Natural C', 'natural-c', (SELECT id FROM public.categories WHERE slug = 'vitamins-and-antioxidants'), 4289, 'Baobab Fruit Powder - Whole-food Vitamin C from the African Tree of Life.', 'Sourced from the African "Tree of Life," this whole-food Vitamin C carries the resilient energy of the savannah to brighten your skin and spirit.', 'A raw source of L-ascorbic acid and prebiotic fiber that enhances collagen production and stabilizes blood sugar levels.', array['Organic Baobab Fruit Powder', 'Natural Vitamin C', 'Prebiotic Fiber']::text[], array['Brightens skin naturally', 'Collagen enhancement', 'Blood sugar balance', 'Immune system support']::text[], 'Stir 2 teaspoons into water, juice, or your favorite morning smoothie.', 'https://images.unsplash.com/photo-1648139347040-857f024f8da4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx2aXRhbWluJTIwYyUyMHBvd2RlciUyMG9yYW5nZSUyMHN1cHBsZW1lbnR8ZW58MXx8fHwxNzcxNzU5NzkyfDA&ixlib=rb-4.1.0&q=80&w=1080', 50, true),
('Activated Charcoal', 'activated-charcoal', (SELECT id FROM public.categories WHERE slug = 'detox-and-cleanse'), 2599, 'Premium Activated Charcoal - Nature''s magnetic cleanser for modern living.', 'Nature''s "magnetic" cleanser that draws out the heavy impurities of modern living, leaving you feeling light and renewed.', 'High-surface-area carbon binds to toxins in the digestive tract via adsorption, preventing them from entering the bloodstream.', array['Activated Coconut Shell Charcoal', 'High-Surface-Area Carbon']::text[], array['Toxin binding support', 'Digestive cleansing', 'Bloating relief', 'Natural detoxification']::text[], 'Mix 1/2 teaspoon in a glass of water. Take 2 hours away from food.', 'https://images.unsplash.com/photo-1534259434801-e3d2427ae102?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhY3RpdmF0ZWQlMjBjaGFyY29hbCUyMHBvd2RlciUyMGRldG94fGVufDF8fHx8MTc3MTc1OTc4NXww&ixlib=rb-4.1.0&q=80&w=1080', 50, true),
('Ashwagandha', 'ashwagandha', (SELECT id FROM public.categories WHERE slug = 'adaptogens-and-stress-support'), 3769, 'Organic Ashwagandha Root - Ancient Ayurvedic strength for stress resilience.', 'An ancient Ayurvedic root that helps the soul stay anchored, providing the "strength of a horse" to endure life''s daily stressors.', 'An adaptogen that regulates the HPA axis to modulate cortisol levels, helping to balance the nervous system.', array['Organic Ashwagandha Root Extract', 'Withanolides', 'Natural Adaptogens']::text[], array['Stress management', 'Cortisol balance', 'Enhanced resilience', 'Nervous system support']::text[], 'Take 500mg daily in capsule form or mix into warm milk before bed.', 'https://images.unsplash.com/photo-1608629483046-50c4a693b37f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhc2h3YWdhbmRoYSUyMHJvb3QlMjBwb3dkZXIlMjBheXVydmVkaWN8ZW58MXx8fHwxNzcxNzU5Nzg1fDA&ixlib=rb-4.1.0&q=80&w=1080', 50, true),
('Neem', 'neem', (SELECT id FROM public.categories WHERE slug = 'blood-purification-and-skin'), 2859, 'Pure Neem Powder - The Village Pharmacy for radiant skin and internal clarity.', 'Known as "The Village Pharmacy," Neem is a sacred purifier used for centuries to manifest radiant skin and internal clarity.', 'Contains bioactive limonoids that offer potent antimicrobial and anti-inflammatory support for the blood.', array['Organic Neem Leaf Powder', 'Limonoids', 'Natural Azadirachtin']::text[], array['Skin radiance', 'Blood purification', 'Antimicrobial support', 'Anti-inflammatory properties']::text[], 'Traditionally taken for internal cleansing or applied as a diluted oil for skin.', 'https://images.unsplash.com/photo-1586787458771-f8115994d98a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxuZWVtJTIwbGVhdmVzJTIwcG93ZGVyJTIwbmF0dXJhbHxlbnwxfHx8fDE3NzE3NTk3ODZ8MA&ixlib=rb-4.1.0&q=80&w=1080', 50, true),
('Castor Oil', 'castor-oil', (SELECT id FROM public.categories WHERE slug = 'topical-wellness-and-lymphatic'), 3509, 'Cold-Pressed Castor Oil - The Palm of Christ for deep tissue healing.', 'A thick, golden oil known as the "Palm of Christ," used to draw out tension and encourage the body''s healing flow.', 'Rich in Ricinoleic acid, which penetrates deep into tissues to stimulate lymphatic drainage.', array['100% Pure Cold-Pressed Castor Oil', 'Ricinoleic Acid', 'Natural Fatty Acids']::text[], array['Lymphatic drainage', 'Deep tissue penetration', 'Hair & scalp nourishment', 'Tension relief']::text[], 'Apply topically as a warm pack or use as a nourishing treatment for hair.', 'https://images.unsplash.com/photo-1596470663178-dc2df28026f7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjYXN0b3IlMjBvaWwlMjBib3R0bGUlMjBuYXR1cmFsfGVufDF8fHx8MTc3MTc1OTc4Nnww&ixlib=rb-4.1.0&q=80&w=1080', 50, true),
('Chamomile', 'chamomile', (SELECT id FROM public.categories WHERE slug = 'herbal-teas-and-relaxation'), 2079, 'Organic Chamomile Flowers - A floral embrace for peace and stillness.', 'A floral embrace that softens the edges of a hard day, inviting a sense of peace and restorative stillness.', 'High in the antioxidant Apigenin, which binds to specific receptors in the brain to reduce anxiety.', array['Organic Chamomile Flowers', 'Apigenin', 'Natural Flavonoids']::text[], array['Reduces anxiety', 'Promotes sleep', 'Digestive calming', 'Antioxidant protection']::text[], 'Steep 1 tablespoon of flowers in hot water for 7 minutes.', 'https://images.unsplash.com/photo-1631037958828-cc7d9a7fd93b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjaGFtb21pbGUlMjBmbG93ZXJzJTIwdGVhJTIwaGVyYnN8ZW58MXx8fHwxNzcxNzU5Nzg2fDA&ixlib=rb-4.1.0&q=80&w=1080', 50, true),
('Star Anise', 'star-anise', (SELECT id FROM public.categories WHERE slug = 'respiratory-and-immune'), 2469, 'Whole Star Anise - Protective spice for respiratory wellness.', 'A beautiful, spice-scented shield that guards the respiratory system and warms the body''s internal fire.', 'A primary natural source of Shikimic Acid, used to inhibit viral replication and support lung health.', array['Whole Star Anise', 'Shikimic Acid', 'Natural Essential Oils']::text[], array['Respiratory protection', 'Viral inhibition support', 'Lung health', 'Warming properties']::text[], 'Add to tea blends or use in cooking to extract potent protective compounds.', 'https://images.unsplash.com/photo-1765118433463-93af73bc8ff9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzdGFyJTIwYW5pc2UlMjBzcGljZSUyMG5hdHVyYWx8ZW58MXx8fHwxNzcxNzU5Nzg3fDA&ixlib=rb-4.1.0&q=80&w=1080', 50, true),
('Nutri Honey', 'nutri-honey', (SELECT id FROM public.categories WHERE slug = 'raw-sweeteners-and-energy'), 3899, 'Raw Wildflower Honey - Living sunshine captured in a jar.', 'Living sunshine captured in a jar. Our honey is an enzymatic powerhouse that carries the healing vibrations of wild blooms.', 'Contains raw polyphenols and natural enzymes that support gut health and provide steady energy.', array['Raw Wildflower Honey', 'Natural Enzymes', 'Polyphenols', 'Bee Pollen']::text[], array['Gut health support', 'Steady energy', 'Allergy relief', 'Natural antimicrobial']::text[], 'Take one teaspoon daily for allergy support or stir into lukewarm tea.', 'https://images.unsplash.com/photo-1719871766551-b9ecf87eee51?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxyYXclMjBob25leSUyMGphciUyMG5hdHVyYWx8ZW58MXx8fHwxNzcxNzU5Nzg3fDA&ixlib=rb-4.1.0&q=80&w=1080', 50, true),
('Magnesium Glycinate', 'magnesium-glycinate', (SELECT id FROM public.categories WHERE slug = 'minerals-and-sleep-support'), 3639, 'Chelated Magnesium Glycinate - The Master Mineral for rest and recovery.', 'The "Master Mineral" for modern rest. It acts as a grounding force for those who find it hard to "switch off" at night.', 'Chelated with Glycine for maximum absorption; supports over 300 enzymatic reactions including ATP production.', array['Magnesium Glycinate', 'Glycine', 'Chelated Minerals']::text[], array['Deep sleep support', 'Muscle relaxation', 'Energy production', 'Nervous system calming']::text[], 'Take 200-400mg approximately 1 hour before bedtime.', 'https://images.unsplash.com/photo-1729704200357-bb60fe204b55?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtYWduZXNpdW0lMjBzdXBwbGVtZW50JTIwY2Fwc3VsZXMlMjB3ZWxsbmVzc3xlbnwxfHx8fDE3NzE3NTk3ODd8MA&ixlib=rb-4.1.0&q=80&w=1080', 50, true),
('Turmeric & Curcumin', 'turmeric-and-curcumin', (SELECT id FROM public.categories WHERE slug = 'anti-inflammatory-and-joint-health'), 4159, 'Organic Turmeric with High-Potency Curcumin - Nature''s golden healer.', 'Nature''s golden healer, bringing warmth and mobility to the joints while brightening the body''s internal landscape.', 'Curcuminoids act as signaling molecules that downregulate inflammatory pathways like NF-kB.', array['Organic Turmeric Root', '95% Curcuminoids', 'Black Pepper Extract']::text[], array['Joint mobility', 'Inflammation modulation', 'Antioxidant power', 'Cardiovascular support']::text[], 'Take with a pinch of black pepper or healthy fats to increase bioavailability.', 'https://images.unsplash.com/photo-1702041295331-840d4d9aa7c9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0dXJtZXJpYyUyMGN1cmN1bWluJTIwcG93ZGVyJTIwZ29sZGVufGVufDF8fHx8MTc3MTc1OTc4OHww&ixlib=rb-4.1.0&q=80&w=1080', 50, true),
('Sea Moss Gel', 'sea-moss-gel', (SELECT id FROM public.categories WHERE slug = 'minerals-and-thyroid-support'), 4549, 'Wild-Harvested Sea Moss Gel - The ocean''s mineral multivitamin.', 'The ocean''s mineral multivitamin, containing 92 of the 102 minerals your body is made of, for total cellular nourishment.', 'High in organic Iodine for thyroid support and Potassium Chloride to help dissolve excess mucus.', array['Wild Irish Sea Moss', 'Organic Iodine', 'Potassium Chloride', '92 Trace Minerals']::text[], array['Thyroid health', 'Mucus dissolution', 'Cellular nourishment', 'Immune support']::text[], 'Add 1-2 tablespoons to smoothies, soups, or teas daily.', 'https://images.unsplash.com/photo-1707868569462-819213af203e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzZWElMjBtb3NzJTIwZ2VsJTIwbmF0dXJhbHxlbnwxfHx8fDE3NzE3NTk3ODh8MA&ixlib=rb-4.1.0&q=80&w=1080', 50, true),
('Elderberry Syrup', 'elderberry-syrup', (SELECT id FROM public.categories WHERE slug = 'immune-support'), 3509, 'Organic Elderberry Syrup - Ancient berry guardian for seasonal protection.', 'An ancient berry-based guardian used for generations to protect the family during the cold, dark months.', 'Anthocyanins in the berries strengthen cell membranes, making it harder for viruses to enter cells.', array['Organic Elderberries', 'Raw Honey', 'Cinnamon', 'Clove', 'Anthocyanins']::text[], array['Seasonal protection', 'Cell membrane strength', 'Antiviral properties', 'Family immune support']::text[], 'Take 1 tablespoon daily for maintenance, or increase frequency if needed.', 'https://images.unsplash.com/photo-1728776448558-fe55e6fb3f3d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxlbGRlcmJlcnJ5JTIwc3lydXAlMjBib3R0bGUlMjBpbW11bmV8ZW58MXx8fHwxNzcxNzU5Nzg4fDA&ixlib=rb-4.1.0&q=80&w=1080', 50, true),
('Spirulina & Chlorella', 'spirulina-and-chlorella', (SELECT id FROM public.categories WHERE slug = 'superfoods-and-detox'), 4809, 'Organic Spirulina & Chlorella Blend - Liquid sunshine for cellular detox.', 'Blue-green algae that act as "liquid sunshine," alkalizing the blood and providing deep cellular detoxification.', 'Exceptionally high in Chlorophyll and bioavailable iron, supporting healthy oxygen transport.', array['Organic Spirulina', 'Cracked-Wall Chlorella', 'Chlorophyll', 'Bioavailable Iron']::text[], array['Blood alkalizing', 'Cellular detox', 'Oxygen transport', 'Nutrient density']::text[], 'Mix powder into water or smoothies; start with a small dose.', 'https://images.unsplash.com/photo-1664956618403-175f565f18be?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzcGlydWxpbmElMjBwb3dkZXIlMjBibHVlJTIwZ3JlZW58ZW58MXx8fHwxNzcxNzU5NzkyfDA&ixlib=rb-4.1.0&q=80&w=1080', 50, true),
('Moringa Powder', 'moringa-powder', (SELECT id FROM public.categories WHERE slug = 'superfoods-and-nutrition'), 3769, 'Organic Moringa Leaf Powder - The Miracle Tree multivitamin.', 'The "Miracle Tree" of the tropics, offering a nutrient-dense multivitamin in its purest, most vibrant plant form.', 'Contains 15x more Potassium than bananas and 17x more Calcium than milk, supporting bone density.', array['Organic Moringa Leaf Powder', 'Plant-Based Calcium', 'Potassium', 'Vitamin A']::text[], array['Bone density support', 'Natural multivitamin', 'Energy boost', 'Plant-based nutrition']::text[], 'Mix 1 teaspoon into savory dishes, green juices, or morning lattes.', 'https://images.unsplash.com/photo-1746707233861-c3663cc5dff2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtb3JpbmdhJTIwbGVhdmVzJTIwZ3JlZW4lMjBwb3dkZXJ8ZW58MXx8fHwxNzcxNzU5NzkzfDA&ixlib=rb-4.1.0&q=80&w=1080', 50, true),
('Black Seed Oil', 'black-seed-oil', (SELECT id FROM public.categories WHERE slug = 'respiratory-and-heart-health'), 4419, 'Cold-Pressed Black Seed Oil - A cure for everything but death.', 'Revered for millennia as a "cure for everything," this potent oil restores the body''s innate healing intelligence.', 'Rich in Thymoquinone, a compound that supports bronchodilation and cardiovascular health.', array['100% Pure Black Seed Oil', 'Thymoquinone', 'Omega Fatty Acids']::text[], array['Respiratory support', 'Heart health', 'Bronchodilation', 'Natural healing']::text[], 'Take 1 teaspoon daily; can be chased with a spoonful of honey.', 'https://images.unsplash.com/photo-1755598603202-f6c6e02aa16b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxibGFjayUyMGN1bWluJTIwc2VlZCUyMG9pbHxlbnwxfHx8fDE3NzE3NTk3OTN8MA&ixlib=rb-4.1.0&q=80&w=1080', 50, true),
('Fulvic & Humic Acid', 'fulvic-and-humic-acid', (SELECT id FROM public.categories WHERE slug = 'minerals-and-cellular-absorption'), 5069, 'Liquid Fulvic & Humic Minerals - Ancient soil wisdom for nutrient uptake.', 'Ancient soil minerals that act as a bridge, helping your cells actually "receive" the nutrients from the food you eat.', 'Acts as a natural chelator that increases the permeability of cell membranes for efficient nutrient uptake.', array['Fulvic Acid', 'Humic Acid', 'Trace Minerals', 'Natural Electrolytes']::text[], array['Enhanced nutrient absorption', 'Cellular permeability', 'Detox support', 'Mineral replenishment']::text[], 'Add a few drops to filtered water daily to remineralize your body.', 'https://images.unsplash.com/photo-1764694187667-f28a05a52c0e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtaW5lcmFsJTIwc3VwcGxlbWVudCUyMGxpcXVpZCUyMGRyb3BzfGVufDF8fHx8MTc3MTc1OTc5M3ww&ixlib=rb-4.1.0&q=80&w=1080', 50, true),
('Milk Thistle', 'milk-thistle', (SELECT id FROM public.categories WHERE slug = 'liver-support-and-detox'), 3249, 'Standardized Milk Thistle Extract - Gentle liver protection and renewal.', 'A gentle, protective reset for the liver, helping to filter out the noise of a toxic world.', 'Contains Silymarin, which stabilizes liver cell membranes and helps the liver regenerate.', array['Milk Thistle Seed Extract', 'Silymarin (80% Extract)', 'Natural Flavonoids']::text[], array['Liver regeneration', 'Cell membrane protection', 'Detox pathway support', 'Antioxidant protection']::text[], 'Best taken as a standardized extract (capsule) or a tea.', 'https://images.unsplash.com/photo-1731970820339-e725b78f55e4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtaWxrJTIwdGhpc3RsZSUyMHNlZWRzJTIwbmF0dXJhbHxlbnwxfHx8fDE3NzE3NTk3ODl8MA&ixlib=rb-4.1.0&q=80&w=1080', 50, true),
('Peppermint Oil', 'peppermint-oil', (SELECT id FROM public.categories WHERE slug = 'digestive-health-and-focus'), 2209, 'Food-Grade Peppermint Essential Oil - Cool relief for digestion and clarity.', 'A breath of fresh air for the digestive system, providing cool relief and mental clarity.', 'Menthol relaxes the smooth muscles of the intestines, reducing bloating and improving bile flow.', array['100% Pure Peppermint Oil', 'Natural Menthol', 'Essential Plant Compounds']::text[], array['Digestive comfort', 'Bloating relief', 'Mental clarity', 'Bile flow support']::text[], 'Use 1-2 drops (food grade) in tea or apply diluted to temples.', 'https://images.unsplash.com/photo-1743620404324-360e5506bcf3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwZXBwZXJtaW50JTIwb2lsJTIwZXNzZW50aWFsJTIwYm90dGxlfGVufDF8fHx8MTc3MTc1OTc4OXww&ixlib=rb-4.1.0&q=80&w=1080', 50, true)
ON CONFLICT (slug) DO NOTHING;

COMMIT;
