// Generates supabase/seed_products_v3.sql from src/app/data/products.ts
// Run: node scripts/gen_seed_v3.cjs
//
// Why v3: previous seeds failed because RLS policies on categories/products
// require is_admin() for INSERT, which rejects SQL-Editor runs by non-admins.
// This seed temporarily disables RLS on the two seeded tables, restores it at
// the end, and uses small idempotent upsert statements (no giant BEGIN/COMMIT
// transaction, no CTEs) so it pastes cleanly into the Supabase SQL Editor.
const fs = require('fs');
let src = fs.readFileSync('/workspace/src/app/data/products.ts', 'utf8');

src = src.replace(/^import[^;]*;/gm, '');                              // drop imports
src = src.replace(/export\s+interface\s+\w+\s*\{[\s\S]*?\n\}/g, '');   // drop interface blocks
src = src.replace(/export\s+const\s+products[^=]*=/, 'const products =');
src = src.split(/const\s+productCategories/)[0];
src = src.replace(/export\s+/g, '');

const fn = new Function(src + '\nreturn products;');
const prods = fn();
console.log('parsed products:', prods.length);

const esc = (s) => String(s).replace(/'/g, "''");
const slugify = (name) =>
  name.toLowerCase().replace(/&/g, 'and').replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');

const cats = [];
prods.forEach((p) => {
  if (p.category && !cats.includes(p.category)) cats.push(p.category);
});

const arrLit = (vals) =>
  (vals && vals.length ? "'" + vals.map(esc).join("','") + "'" : null);

let out = `-- Diatomlife product & category seed — v3 (auto-generated by scripts/gen_seed_v3.cjs)
-- Source of truth: src/app/data/products.ts (${prods.length} products, ${cats.length} categories)
--
-- FIXES vs v2:
--   * Temporarily DISABLES row security on categories/products (v2 failed here:
--     RLS insert policies require is_admin(), which rejects SQL-Editor runs).
--   * One small statement per row — no giant multi-row VALUES block, no CTEs,
--     no BEGIN/COMMIT wrapper (Supabase editor-friendly).
--   * Idempotent upserts keyed on slug; re-running also refreshes prices/text.
--   * Restores RLS at the end. Run AFTER full_setup.sql. Prices are USD*130 KES placeholders.

-- 0) Allow seeding regardless of RLS admin check (restored in step 3 below)
alter table public.categories disable row security;
alter table public.products disable row security;

-- 1) Categories (${cats.length})
`;

cats.forEach((c, i) => {
  const slug = slugify(c);
  out +=
    `insert into public.categories (name, slug, sort_order)\n` +
    `values ('${esc(c)}', '${slug}', ${i + 1})\n` +
    `on conflict (slug) do update set name = excluded.name, sort_order = excluded.sort_order;\n`;
});

out += `\n-- 2) Products (${prods.length})\n`;

prods.forEach((p) => {
  const slug = slugify(p.name);
  const catSlug = slugify(p.category);
  const price = Math.round((p.price || 0) * 130);
  out +=
    `insert into public.products\n` +
    `  (name, slug, category_id, price_kes, description, holistic_story, scientific_why,\n` +
    `   ingredients, benefits, usage, image_url, stock_quantity, is_active)\n` +
    `values (\n` +
    `  '${esc(p.name)}',\n` +
    `  '${slug}',\n` +
    `  (select id from public.categories where slug = '${catSlug}'),\n` +
    `  ${price},\n` +
    `  '${esc(p.description || '')}',\n` +
    `  '${esc(p.holisticStory || p.story || '')}',\n` +
    `  '${esc(p.scientificWhy || p.science || '')}',\n` +
    `  array[${arrLit(p.ingredients) ?? ''}]::text[],\n` +
    `  array[${arrLit(p.benefits) ?? ''}]::text[],\n` +
    `  '${esc(p.usage || p.usageInstructions || '')}',\n` +
    `  '${esc(p.image || p.imageUrl || '')}',\n` +
    `  50,\n` +
    `  true\n` +
    `)\n` +
    `on conflict (slug) do update set\n` +
    `  name = excluded.name,\n` +
    `  category_id = excluded.category_id,\n` +
    `  price_kes = excluded.price_kes,\n` +
    `  description = excluded.description,\n` +
    `  holistic_story = excluded.holistic_story,\n` +
    `  scientific_why = excluded.scientific_why,\n` +
    `  ingredients = excluded.ingredients,\n` +
    `  benefits = excluded.benefits,\n` +
    `  usage = excluded.usage,\n` +
    `  image_url = excluded.image_url,\n` +
    `  updated_at = now();\n`;
});

out += `
-- 3) Restore row-level security (public read stays via the policies in full_setup.sql)
alter table public.categories enable row security;
alter table public.products enable row security;

-- 4) Verify (optional): should return ${cats.length} and ${prods.length}
-- select count(*) from public.categories;
-- select count(*) from public.products;
`;

fs.writeFileSync('/workspace/supabase/seed_products_v3.sql', out);
console.log('wrote supabase/seed_products_v3.sql');
